### ISSUE TITLE
Manhacks thrown by Metrocops aren't assigned a team correctly

### ISSUE THREAD

**Issue by surprise0451** [RaraFolf/TF2HLCoop#11]
Recreate bug: Build a sentry, have a Metrocop throw a Manhack. The sentry will not target the Manhack. 

It also appears thrown Manhacks are not assigned to the blue team, as their kill icon is black rather than blue.

**Comment by Benoist3012** [comment]
*Bump* I forgot to put close #11 in my pull request, can someone come here and close this issue?
