### ISSUE TITLE
Issue With TF_Coop_english

### ISSUE THREAD

**Issue by ckthesorrow** [RaraFolf/TF2HLCoop#27]
My Score Board Performance report weapons etc say like " # TF_ " I tried redownloading the tf_coop_english and the game no luck. Anyway To Fix This? Thanks

**Comment by RaraFolf** [comment]
GitHub tends to mangle localization files for the Source engine, so just copy the text from here https://raw.githubusercontent.com/RaraFolf/TF2HLCoop/master/game/tf_coop/resource/tf_coop_english.txt and paste it into the tf_coop_english.txt file
