### ISSUE TITLE
Make Spy as fast as Medic like in live TF2

### ISSUE THREAD

**Issue by agrastiOs** [RaraFolf/TF2HLCoop#32]
I don't remember the numbers, but making the Spy as fast as the Medic like in live TF2 would make Spy more useful.

**Comment by NicknineTheEagle** [comment]
I don't see a point in doing in LF as Spy is already faster than any humanoid NPCs.

**Comment by agrastiOs** [comment]
Well, not Fast Zombies.
Thing is, Spy is kinda useless against Zombies, considering Zombies notice the Spy behind them, making them almost impossible to backstab. With more speed the Spy could trickstab the Zombies. 
I suggest the speed up the Spy and see how it goes.

**Comment by NicknineTheEagle** [comment]
I doubt extra 20 HU/s are going to make a difference with zombies.

**Comment by agrastiOs** [comment]
Will try to test that out in my branch.
