### ISSUE TITLE
Backstab animation is delayed

### ISSUE THREAD

**Issue by agrastiOs** [RaraFolf/TF2HLCoop#33]
Backstab animation only appears after few seconds. Backstabbing before the animation starts do the normal stab animation, but not the backstabbing animation.

**Comment by NicknineTheEagle** [comment]
This description is kind of confusing, can you post a video?

**Comment by agrastiOs** [comment]
Couldn't find any videos containing that and will only be able to record tomorrow.

1. The Spy goes behind a Combine Soldier.
2. Instead of instantly raising the hand, Spy does so after few seconds.

**Comment by NicknineTheEagle** [comment]
This is a normal behavior, it's how Knife acted until Scout Update released in 2009.
