### ISSUE TITLE
Steam Overlay doesn't work or open

### ISSUE THREAD

**Issue by ejg-steam** [RaraFolf/TF2HLCoop#38]
Shift+Tab does nothing, neither does checking the "use overlay" option in game properties.

**Comment by NicknineTheEagle** [comment]
Seems to be the case with all Source mods and not just LF in particular. Reporty this to Valve.

**Comment by Msalinas2877** [comment]
this is not a problem with our mod, this is a steam issue

**Comment by ejg-steam** [comment]
Hm, could've sworn I used to be able to open it in TF2C. Will do.
