### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by raidensnake** [RaraFolf/TF2HLCoop#4]
I noticed a few issues.
1. players get stuck in small doorways and have to noclip to get through.
2. the textures like the target are messed up.
3. in some areas you can't continue for example helping barney take the shields and turrets down in that museum building.
4. map transitions don't work.
5. no player audio is heard.
6. the mod randomly crashes and only works using release build and not debug otherwise it lags like hell.
7. TF2 assets weren't loaded in the gameinfo.txt file causing the mod to crash.

**Comment by NicknineTheEagle** [comment]
1. tf2c_use_hl2_player_hull 1
2. What target?
3. That area has not been tested yet.
4. Proper nap transitions do not and will not ever work in multiplayer since they rely on save/load system.

All other issues are most likely caused by you using wrong assets. Do not use live TF2 or TF2C assets with

**Comment by raidensnake** [comment]
2. the crosshair is messed up/
3. d3_c17_6a
and if I don't load anything extra the mod doesn't work at all.

**Comment by NicknineTheEagle** [comment]
As stated above, don't use live TF2 assets with this code. I'm surprised it even works at all that way.
